#!/usr/bin/env ruby

require_relative 'lib/cheer'

def ask_for_name_again
  puts "I'm sorry, what was your name again?"
  gets
end


puts "Hello, what's your name?"
name = gets.chomp

while name.empty?
  name = ask_for_name_again
end

puts Cheer.for_person(name)

puts "Hey #{name.chomp}, what's your birthday? (mm/dd)"
birthday_string = gets
puts Cheer.for_birthday(birthday_string)
