#!/usr/bin/env ruby

require_relative 'lib/cheer'

puts "Hello, what's your name?"
name = gets
puts Cheer.for_person(name)

# This is commented as example only - don't commit!
#puts "Hey #{name}, what's your birthday? (mm/dd)"
#birthday_string = gets
#puts Cheer.for_birthday(birthday_string)
